import { ContentEntry } from '../engine/types';

export const contentRegistry: ContentEntry[] = [
  // ─── 테스트 (바이럴/공유 최우선) ───
  {
    slug: 'hell-balance',
    trending: true,
    category: 'test',
    type: 'balance-game',
    title: '지옥의 밸런스 게임',
    subtitle: '둘 다 싫어도 하나는 골라야 해',
    description: '똥맛 카레 vs 카레맛 똥, 전 애인과 한 직장 vs 전 애인 부모님과 한집... 15개의 지옥 같은 선택지 중 하나를 골라보세요. 당신의 선택이 당신의 인격을 드러냅니다 (아닐 수도 있음).',
    tags: ['밸런스게임', '유머', '침착맨', '랜덤'],
    emoji: '😈',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 15,
  },
  {
    slug: 'red-flag-test',
    trending: true,
    category: 'test',
    type: 'score-test',
    title: '나의 Red Flag 레벨',
    subtitle: '연애에서 "이 사람 조금 이상한데?" 느낌을 주는 행동 체크',
    description: 'Red Flag(레드 플래그)란 연애에서 상대에게 불안감이나 불쾌감을 줄 수 있는 행동 습관을 말합니다. 집착, 감정 조절 어려움, 과도한 의심 등이 대표적이에요. 나는 얼마나 해당될까요? 50개 항목 중 랜덤 12문항으로 체크해보세요.',
    tags: ['레드플래그', '연애', '심리', '자기진단'],
    emoji: '🚩',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 12,
  },
  {
    slug: 'mbti-situation',
    trending: true,
    category: 'test',
    type: 'mbti-test',
    title: 'MBTI 상황 테스트',
    subtitle: '설문지 말고, 실제 상황으로 알아보는 MBTI',
    description: '딱딱한 설문지 대신 12개의 실제 상황으로 나의 MBTI 성향을 알아보세요. E/I, S/N, T/F, J/P 4가지 차원을 상황별로 분석합니다.',
    tags: ['MBTI', '성격', '심리테스트', '유형'],
    emoji: '🧬',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 12,
    resultCount: 16,
  },
  {
    slug: 'brain-rot-level',
    trending: true,
    category: 'test',
    type: 'score-test',
    title: '뇌 썩음 레벨 측정기',
    subtitle: '당신의 뇌는 얼마나 썩었나요?',
    description: '미국에서 유행 중인 "Brain Rot" 자가진단. 쇼츠, 밈, 알고리즘에 얼마나 잠식됐는지 10개의 질문으로 솔직하게 확인해보세요. 결과가 두렵다면 이미 늦은 것일 수도...',
    tags: ['뇌썩음', '브레인롯', 'GenZ', '쇼츠', '인터넷'],
    emoji: '🧟',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'npc-test',
    trending: true,
    category: 'test',
    type: 'score-test',
    title: 'NPC 테스트',
    subtitle: '나는 내 인생의 주인공인가, NPC인가?',
    description: '미국 밈에서 유행 중인 "Main Character vs NPC" 개념. 당신은 스스로 선택하고 행동하는 주인공인가요, 아니면 누군가의 배경에 등장하는 NPC인가요? 10개의 질문으로 확인해보세요.',
    tags: ['NPC', '주인공', '자기계발', '밈', '인생'],
    emoji: '🎮',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'chatroom-role-test',
    category: 'test',
    type: 'personality-test',
    title: '단톡방 역할 유형 테스트',
    subtitle: '단톡방에서 나는 어떤 존재일까?',
    description: '10개의 질문으로 단톡방에서의 당신의 역할을 알아보세요. 분위기 메이커? 읽씹 장인? 정보통? 당신의 단톡방 포지션을 확인해보세요.',
    tags: ['테스트', '유형', '단톡방', '카톡', 'MBTI'],
    emoji: '💬',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B', 'C'], coupangCount: 1 },
    questionCount: 10,
    resultCount: 8,
  },
  {
    slug: 'work-meeting-type',
    category: 'test',
    type: 'personality-test',
    title: '회의 포지션 유형 테스트',
    subtitle: '회의실에서 당신의 진짜 역할은?',
    description: '10개의 질문으로 회의에서의 당신의 포지션을 분석합니다. 리더형? 아이디어뱅크? 조율자? 회의 속 진짜 당신을 만나보세요.',
    tags: ['테스트', '유형', '회의', '직장', '포지션'],
    emoji: '🏢',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B', 'C'], coupangCount: 1 },
    questionCount: 10,
    resultCount: 8,
  },

  {
    slug: 'love-language-test',
    trending: true,
    category: 'test',
    type: 'love-language',
    title: '나의 연애 언어 테스트',
    subtitle: '당신이 사랑받는다고 느끼는 방식은?',
    description: '게리 채프먼의 "5가지 사랑의 언어" 기반 테스트. 당신이 연애에서 가장 중요하게 여기는 것이 뭔지 알아보세요 — 말로 표현받기, 함께하는 시간, 선물, 도움받기, 스킨십 중 어떤 언어로 사랑을 느끼나요? 전 세계적으로 가장 많이 공유되는 연애 테스트 중 하나입니다.',
    tags: ['연애언어', '사랑', '관계', '심리', '커플'],
    emoji: '💝',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B', 'C'], coupangCount: 1 },
    questionCount: 15,
    resultCount: 5,
  },
  {
    slug: 'attachment-style-test',
    trending: true,
    category: 'test',
    type: 'attachment-style',
    title: '나의 애착 유형 테스트',
    subtitle: '연애할 때 나는 안정형인가, 불안형인가?',
    description: '심리학 기반 애착 이론 테스트. 안정형, 불안형, 회피형, 혼란형 4가지 유형 중 어디에 해당하는지 12개의 상황 질문으로 알아보세요. 왜 연애가 힘들었는지 이해하는 데 도움이 됩니다. 미국 심리 커뮤니티에서 폭발적으로 공유되는 테스트입니다.',
    tags: ['애착유형', '심리', '연애', '자기이해', '관계'],
    emoji: '🫂',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B', 'C'], coupangCount: 1 },
    questionCount: 12,
    resultCount: 4,
  },
  {
    slug: 'gifted-burnout',
    trending: true,
    category: 'test',
    type: 'score-test',
    title: '영재 번아웃 테스트',
    subtitle: '어릴 때 "넌 특별해"라는 말 많이 들었나요?',
    description: '"Gifted Kid Burnout" - 미국 틱톡에서 수천만 뷰를 기록한 개념. 어릴 때 공부를 잘 하거나 재능이 있다는 말을 많이 들은 사람들이 성인이 되어 겪는 번아웃 패턴. 칭찬받기 위해 살았던 어린 시절의 상처가 지금 당신에게 영향을 주고 있을 수 있습니다.',
    tags: ['영재번아웃', '번아웃', '틱톡', '심리', '자기이해'],
    emoji: '🎓',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 12,
  },
  {
    slug: 'moral-dilemma',
    category: 'test',
    type: 'balance-game',
    title: '도덕 딜레마 게임',
    subtitle: '당신의 도덕 기준은 어디까지인가요?',
    description: '트롤리 문제부터 현실 속 도덕 딜레마까지. 철학자들이 수백 년간 논쟁해온 질문들을 선택지로 만들었습니다. 정답은 없지만 당신의 선택이 당신의 가치관을 보여줍니다. 서양 철학 수업에서 가장 많이 쓰이는 사고 실험을 게임으로 즐겨보세요.',
    tags: ['도덕딜레마', '철학', '사고실험', '트롤리문제', '가치관'],
    emoji: '⚖️',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 15,
  },

  // ─── 운세 (데일리 재방문 유도) ───
  {
    slug: 'today-fortune',
    trending: true,
    category: 'fortune',
    type: 'fortune',
    title: '오늘의 운세',
    subtitle: '생년월일로 보는 오늘 하루',
    description: '생년월일을 입력하면 오늘의 총운, 연애, 금전, 일, 컨디션 운세를 확인할 수 있습니다. 같은 날짜에는 같은 기본 운세가 나오지만, 매일 조금씩 달라지는 조언도 함께 제공됩니다.',
    tags: ['운세', '오늘', '생년월일', '데일리'],
    emoji: '🔮',
    inputSchema: [
      { key: 'birthdate', label: '생년월일', type: 'date', required: true, placeholder: '1990-01-15' },
      { key: 'name', label: '이름 (선택)', type: 'text', required: false, placeholder: '홍길동' },
    ],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B', 'C'], coupangCount: 2 },
  },
  {
    slug: 'saju-lite',
    category: 'fortune',
    type: 'saju',
    title: '1분 사주',
    subtitle: '가볍게 보는 나의 기운과 흐름',
    description: '복잡한 만세력 없이, 생년월일만으로 현재의 흐름(상승/정체/정리)과 은유적 기운(불/물/바람/흙), 균형 키워드를 확인해보세요.',
    tags: ['사주', '기운', '흐름', '간단'],
    emoji: '☯️',
    inputSchema: [
      { key: 'birthdate', label: '생년월일', type: 'date', required: true, placeholder: '1990-01-15' },
      { key: 'name', label: '이름 (선택)', type: 'text', required: false, placeholder: '홍길동' },
    ],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B', 'C'], coupangCount: 2 },
  },

  // ─── 퀴즈 ───
  {
    slug: 'one-minute-quiz',
    trending: true,
    category: 'quiz',
    type: 'quiz',
    title: '1분 상식 퀴즈',
    subtitle: '매일 바뀌는 10문항 도전',
    description: '매일 새로운 10개의 상식 문제에 도전하세요. 같은 날에는 같은 문제가 출제되니 친구와 점수를 비교해볼 수도 있습니다.',
    tags: ['퀴즈', '상식', '매일', '도전'],
    emoji: '🧠',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'physics-quiz',
    category: 'quiz',
    type: 'quiz',
    title: '1분 물리 퀴즈',
    subtitle: '힘, 에너지, 파동 — 고교 물리 총정리',
    description: '뉴턴의 법칙부터 전자기, 열역학까지 고교 물리 핵심 개념을 퀴즈로 확인하세요. 30문제 풀에서 매일 10문제가 무작위로 출제됩니다. 친구와 정답률을 비교해보세요!',
    tags: ['퀴즈', '물리', '과학', '도전', '고교'],
    emoji: '⚛️',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'chemistry-quiz',
    category: 'quiz',
    type: 'quiz',
    title: '1분 화학 퀴즈',
    subtitle: '원소, 결합, 반응 — 고교 화학 총정리',
    description: '주기율표부터 산화환원, 화학평형까지 고교 화학 핵심을 퀴즈로 점검하세요. 30문제 풀에서 매일 10문제가 무작위로 출제됩니다. 오늘의 화학 점수는?',
    tags: ['퀴즈', '화학', '과학', '도전', '원소'],
    emoji: '🧪',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'biology-quiz',
    category: 'quiz',
    type: 'quiz',
    title: '1분 생물 퀴즈',
    subtitle: '세포, 유전, 생태 — 고교 생물 총정리',
    description: 'DNA, 세포 소기관, 유전 법칙, 인체 구조까지 고교 생물 핵심을 퀴즈로 확인하세요. 30문제 풀에서 매일 10문제가 무작위로 출제됩니다.',
    tags: ['퀴즈', '생물', '과학', '도전', '유전'],
    emoji: '🔬',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'world-capitals-quiz',
    category: 'quiz',
    type: 'quiz',
    title: '1분 세계 수도 퀴즈',
    subtitle: '전 세계 수도를 얼마나 아시나요?',
    description: '미국의 수도가 뉴욕이라고 생각했다면? 세계 30개국 수도 퀴즈에 도전하세요. 매일 10문제가 무작위로 출제됩니다. 친구보다 많이 맞춰보세요!',
    tags: ['퀴즈', '수도', '세계', '지리', '도전'],
    emoji: '🗺️',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'world-history-quiz',
    category: 'quiz',
    type: 'quiz',
    title: '1분 세계사 퀴즈',
    subtitle: '역사의 결정적 순간들을 기억하나요?',
    description: '프랑스 혁명, 세계대전, 냉전까지 인류 역사의 핵심 사건을 퀴즈로 확인하세요. 30문제 풀에서 매일 10문제가 무작위로 출제됩니다.',
    tags: ['퀴즈', '세계사', '역사', '도전', '상식'],
    emoji: '📜',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },

  // ─── 서양 바이럴 테스트 ───
  {
    slug: 'rizz-test',
    trending: true,
    category: 'test',
    type: 'score-test',
    title: '나의 리즈력은? (Rizz Test)',
    subtitle: '상대를 자연스럽게 매혹하는 능력, 측정해봤어?',
    description: '"Rizz"란 TikTok에서 폭발적으로 유행한 단어로, 말 한마디·눈빛·태도로 상대를 자연스럽게 이끄는 매력 능력입니다. 당신의 리즈력은 몇 점일까요? 15개 중 10개 문항으로 체크해보세요.',
    tags: ['리즈력', '매력', 'Rizz', '연애', '카리스마'],
    emoji: '✨',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
    resultCount: 4,
  },
  {
    slug: 'delulu-test',
    trending: true,
    category: 'test',
    type: 'score-test',
    title: '나는 망상러? (Delulu Test)',
    subtitle: '서양에서 대유행 중인 망상 지수 체크',
    description: '"Delulu(망상러)"는 TikTok·Instagram에서 유행하는 신조어로, 현실과 동떨어진 로맨틱 상상을 하는 경향을 말합니다. 내 카톡 분석, 혼자 만든 시나리오... 당신의 망상 지수는 몇 점일까요?',
    tags: ['망상러', 'Delulu', '연애', '공감', 'TikTok'],
    emoji: '🌈',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
    resultCount: 4,
  },
  {
    slug: 'main-character-syndrome',
    trending: true,
    category: 'test',
    type: 'score-test',
    title: '주인공 증후군 테스트',
    subtitle: '내 삶은 내가 주인공인 드라마인가?',
    description: '"Main Character Syndrome(주인공 증후군)"은 자신을 삶의 주인공으로 여기고 BGM이 들리는 것 같은 몰입감을 느끼는 현상입니다. 서양에서 Z세대를 중심으로 크게 유행하고 있어요. 당신의 주인공 에너지는?',
    tags: ['주인공증후군', 'MainCharacter', '자아', 'Z세대', '공감'],
    emoji: '🎬',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
    resultCount: 4,
  },
  {
    slug: 'touch-grass-test',
    trending: true,
    category: 'test',
    type: 'score-test',
    title: '현실 접촉 테스트 (Touch Grass)',
    subtitle: '당신은 얼마나 오프라인 세계와 단절됐나요?',
    description: '"Touch Grass(잔디 좀 만져)"는 서양 인터넷에서 "화면 좀 그만 보고 밖에 나가라"는 뜻으로 쓰이는 밈입니다. 당신의 현실 접촉 지수를 체크해보세요. 혹시 이미 디지털 영구 거주자가 된 건 아닐까요?',
    tags: ['TouchGrass', '인터넷중독', '디지털디톡스', '밈', '공감'],
    emoji: '🌿',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
    resultCount: 4,
  },
  {
    slug: 'sigma-mindset',
    category: 'test',
    type: 'score-test',
    title: '시그마 마인드셋 테스트',
    subtitle: '당신은 고독한 늑대? 시그마 그라인드셋 체크',
    description: '"Sigma(시그마)"는 사회적 위계에 얽매이지 않고 독자적으로 성공을 추구하는 스타일을 뜻하는 서양 밈입니다. 알파·베타와는 다른, 고독하지만 강력한 시그마의 특성이 당신에게 있나요?',
    tags: ['시그마', 'Sigma', '그라인드셋', '자기계발', '밈'],
    emoji: '🐺',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
    resultCount: 4,
  },

  // ─── 타로·별자리 운세 ───
  {
    slug: 'tarot-daily',
    trending: true,
    category: 'fortune',
    type: 'tarot',
    title: '오늘의 타로 카드',
    subtitle: '마음이 끌리는 3장을 선택해보세요',
    description: '22장의 메이저 아르카나 중 직감으로 3장을 뽑아보세요. 과거·현재·미래의 흐름을 타로로 읽어드립니다. 타로는 현재 에너지를 반영하는 거울입니다.',
    tags: ['타로', '운세', '카드점', '직관', '오늘의운세'],
    emoji: '🃏',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 2 },
  },
  {
    slug: 'zodiac-fortune',
    trending: true,
    category: 'fortune',
    type: 'zodiac',
    title: '별자리 운세',
    subtitle: '생년월일로 확인하는 나의 별자리',
    description: '12개 별자리(황도12궁)를 기반으로 당신의 성격과 오늘의 운세를 확인해보세요. 연애운, 재물운, 건강운까지 한 번에 확인할 수 있습니다.',
    tags: ['별자리', '운세', '호로스코프', '황도12궁', '오늘의운세'],
    emoji: '⭐',
    inputSchema: [
      { key: 'birthdate', label: '생년월일', type: 'date', required: true, placeholder: '1990-01-15' },
    ],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 2 },
  },

  // ─── 게임 ───
  {
    slug: 'reaction-tap',
    trending: true,
    category: 'game',
    type: 'game',
    title: '반응 속도 게임',
    subtitle: '1분 안에 얼마나 빠르게 반응할 수 있을까?',
    description: '화면이 바뀌는 순간 최대한 빠르게 탭하세요. 평균 반응 속도와 등급을 확인하고, 최고 기록에 도전해보세요.',
    tags: ['게임', '반응속도', '탭', '도전'],
    emoji: '⚡',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
  },
  {
    slug: 'color-memory',
    category: 'game',
    type: 'game',
    title: '색깔 기억 게임',
    subtitle: '몇 단계까지 기억할 수 있을까?',
    description: '색깔이 순서대로 점등됩니다. 순서를 기억하고 그대로 탭하세요! 한 단계씩 길어지는 시퀀스를 얼마나 기억할 수 있는지 도전해보세요. 전 세계적으로 사랑받는 기억력 게임입니다.',
    tags: ['게임', '기억력', '색깔', '도전', '집중력'],
    emoji: '🎨',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
  },
  {
    slug: 'number-memory',
    category: 'game',
    type: 'game',
    title: '숫자 기억 게임',
    subtitle: '몇 자리 숫자까지 기억할 수 있을까?',
    description: '숫자가 잠깐 보였다가 사라집니다. 기억해서 정확하게 입력해보세요! 숫자가 점점 길어져 어려워지는 두뇌 트레이닝 게임입니다.',
    tags: ['게임', '기억력', '숫자', '도전', '두뇌'],
    emoji: '🔢',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
  },
];

export function getContentBySlug(slug: string): ContentEntry | undefined {
  return contentRegistry.find(c => c.slug === slug);
}

export function getContentByCategory(category: string): ContentEntry[] {
  return contentRegistry.filter(c => c.category === category);
}

export function getAllCategories(): { id: string; label: string; emoji: string }[] {
  return [
    { id: 'test', label: '테스트', emoji: '📝' },
    { id: 'fortune', label: '운세', emoji: '🔮' },
    { id: 'quiz', label: '퀴즈', emoji: '🧠' },
    { id: 'game', label: '게임', emoji: '🎮' },
  ];
}
