import { ContentEntry } from '../engine/types';

export const contentRegistry: ContentEntry[] = [
  // ─── 운세 ───
  {
    slug: 'today-fortune',
    trending: true,
    category: 'fortune',
    type: 'fortune',
    title: '오늘의 운세',
    subtitle: '생년월일로 보는 오늘 하루',
    description: '생년월일을 입력하면 오늘의 총운, 연애, 금전, 일, 컨디션 운세를 확인할 수 있습니다. 같은 날짜에는 같은 기본 운세가 나오지만, 매일 조금씩 달라지는 조언도 함께 제공됩니다.',
    tags: ['운세', '오늘', '생년월일', '데일리'],
    emoji: '🔮',
    inputSchema: [
      { key: 'birthdate', label: '생년월일', type: 'date', required: true, placeholder: '1990-01-15' },
      { key: 'name', label: '이름 (선택)', type: 'text', required: false, placeholder: '홍길동' },
    ],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B', 'C'], coupangCount: 2 },
  },
  {
    slug: 'saju-lite',
    category: 'fortune',
    type: 'saju',
    title: '1분 사주',
    subtitle: '가볍게 보는 나의 기운과 흐름',
    description: '복잡한 만세력 없이, 생년월일만으로 현재의 흐름(상승/정체/정리)과 은유적 기운(불/물/바람/흙), 균형 키워드를 확인해보세요.',
    tags: ['사주', '기운', '흐름', '간단'],
    emoji: '☯️',
    inputSchema: [
      { key: 'birthdate', label: '생년월일', type: 'date', required: true, placeholder: '1990-01-15' },
      { key: 'name', label: '이름 (선택)', type: 'text', required: false, placeholder: '홍길동' },
    ],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B', 'C'], coupangCount: 2 },
  },

  // ─── 테스트 ───
  {
    slug: 'chatroom-role-test',
    category: 'test',
    type: 'personality-test',
    title: '단톡방 역할 유형 테스트',
    subtitle: '단톡방에서 나는 어떤 존재일까?',
    description: '10개의 질문으로 단톡방에서의 당신의 역할을 알아보세요. 분위기 메이커? 읽씹 장인? 정보통? 당신의 단톡방 포지션을 확인해보세요.',
    tags: ['테스트', '유형', '단톡방', '카톡', 'MBTI'],
    emoji: '💬',
    inputSchema: [],
    adPolicy: { questionAds: 1, resultSlots: ['A', 'B', 'C'], coupangCount: 1 },
    questionCount: 10,
    resultCount: 8,
  },
  {
    slug: 'work-meeting-type',
    category: 'test',
    type: 'personality-test',
    title: '회의 포지션 유형 테스트',
    subtitle: '회의실에서 당신의 진짜 역할은?',
    description: '10개의 질문으로 회의에서의 당신의 포지션을 분석합니다. 리더형? 아이디어뱅크? 조율자? 회의 속 진짜 당신을 만나보세요.',
    tags: ['테스트', '유형', '회의', '직장', '포지션'],
    emoji: '🏢',
    inputSchema: [],
    adPolicy: { questionAds: 1, resultSlots: ['A', 'B', 'C'], coupangCount: 1 },
    questionCount: 10,
    resultCount: 8,
  },

  // ─── 퀴즈 ───
  {
    slug: 'one-minute-quiz',
    category: 'quiz',
    type: 'quiz',
    title: '1분 상식 퀴즈',
    subtitle: '매일 바뀌는 10문항 도전',
    description: '매일 새로운 10개의 상식 문제에 도전하세요. 같은 날에는 같은 문제가 출제되니 친구와 점수를 비교해볼 수도 있습니다.',
    tags: ['퀴즈', '상식', '매일', '도전'],
    emoji: '🧠',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'physics-quiz',
    category: 'quiz',
    type: 'quiz',
    title: '1분 물리 퀴즈',
    subtitle: '힘, 에너지, 파동 — 고교 물리 총정리',
    description: '뉴턴의 법칙부터 전자기, 열역학까지 고교 물리 핵심 개념을 퀴즈로 확인하세요. 30문제 풀에서 매일 10문제가 무작위로 출제됩니다. 친구와 정답률을 비교해보세요!',
    tags: ['퀴즈', '물리', '과학', '도전', '고교'],
    emoji: '⚛️',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'chemistry-quiz',
    category: 'quiz',
    type: 'quiz',
    title: '1분 화학 퀴즈',
    subtitle: '원소, 결합, 반응 — 고교 화학 총정리',
    description: '주기율표부터 산화환원, 화학평형까지 고교 화학 핵심을 퀴즈로 점검하세요. 30문제 풀에서 매일 10문제가 무작위로 출제됩니다. 오늘의 화학 점수는?',
    tags: ['퀴즈', '화학', '과학', '도전', '원소'],
    emoji: '🧪',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'biology-quiz',
    category: 'quiz',
    type: 'quiz',
    title: '1분 생물 퀴즈',
    subtitle: '세포, 유전, 생태 — 고교 생물 총정리',
    description: 'DNA, 세포 소기관, 유전 법칙, 인체 구조까지 고교 생물 핵심을 퀴즈로 확인하세요. 30문제 풀에서 매일 10문제가 무작위로 출제됩니다.',
    tags: ['퀴즈', '생물', '과학', '도전', '유전'],
    emoji: '🔬',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'world-capitals-quiz',
    category: 'quiz',
    type: 'quiz',
    title: '1분 세계 수도 퀴즈',
    subtitle: '전 세계 수도를 얼마나 아시나요?',
    description: '미국의 수도가 뉴욕이라고 생각했다면? 세계 30개국 수도 퀴즈에 도전하세요. 매일 10문제가 무작위로 출제됩니다. 친구보다 많이 맞춰보세요!',
    tags: ['퀴즈', '수도', '세계', '지리', '도전'],
    emoji: '🗺️',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },
  {
    slug: 'world-history-quiz',
    category: 'quiz',
    type: 'quiz',
    title: '1분 세계사 퀴즈',
    subtitle: '역사의 결정적 순간들을 기억하나요?',
    description: '프랑스 혁명, 세계대전, 냉전까지 인류 역사의 핵심 사건을 퀴즈로 확인하세요. 30문제 풀에서 매일 10문제가 무작위로 출제됩니다.',
    tags: ['퀴즈', '세계사', '역사', '도전', '상식'],
    emoji: '📜',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
  },

  // ─── 테스트 (추가) ───
  {
    slug: 'hell-balance',
    category: 'test',
    type: 'balance-game',
    title: '지옥의 밸런스 게임',
    subtitle: '둘 다 싫어도 하나는 골라야 해',
    description: '똥맛 카레 vs 카레맛 똥, 전 애인과 한 직장 vs 전 애인 부모님과 한집... 15개의 지옥 같은 선택지 중 하나를 골라보세요. 당신의 선택이 당신의 인격을 드러냅니다 (아닐 수도 있음).',
    tags: ['밸런스게임', '유머', '침착맨', '랜덤'],
    emoji: '😈',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 15,
    trending: true,
  },
  {
    slug: 'red-flag-test',
    category: 'test',
    type: 'score-test',
    title: '나의 Red Flag 레벨',
    subtitle: '전 연인들이 이미 모임을 가졌을 수도 있어요',
    description: '당신은 연애에서 얼마나 많은 레드플래그를 보유하고 있나요? 12개의 솔직한 질문으로 확인해보세요. 결과가 무섭더라도 직면해야 합니다.',
    tags: ['레드플래그', '연애', '심리', '자기진단'],
    emoji: '🚩',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 12,
    trending: true,
  },
  {
    slug: 'mbti-situation',
    category: 'test',
    type: 'mbti-test',
    title: 'MBTI 상황 테스트',
    subtitle: '설문지 말고, 실제 상황으로 알아보는 MBTI',
    description: '딱딱한 설문지 대신 12개의 실제 상황으로 나의 MBTI 성향을 알아보세요. E/I, S/N, T/F, J/P 4가지 차원을 상황별로 분석합니다.',
    tags: ['MBTI', '성격', '심리테스트', '유형'],
    emoji: '🧬',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 12,
    resultCount: 16,
    trending: true,
  },
  {
    slug: 'brain-rot-level',
    category: 'test',
    type: 'score-test',
    title: '뇌 썩음 레벨 측정기',
    subtitle: '당신의 뇌는 얼마나 썩었나요?',
    description: '미국에서 유행 중인 "Brain Rot" 자가진단. 쇼츠, 밈, 알고리즘에 얼마나 잠식됐는지 10개의 질문으로 솔직하게 확인해보세요. 결과가 두렵다면 이미 늦은 것일 수도...',
    tags: ['뇌썩음', '브레인롯', 'GenZ', '쇼츠', '인터넷'],
    emoji: '🧠',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
    trending: true,
  },
  {
    slug: 'npc-test',
    category: 'test',
    type: 'score-test',
    title: 'NPC 테스트',
    subtitle: '나는 내 인생의 주인공인가, NPC인가?',
    description: '미국 밈에서 유행 중인 "Main Character vs NPC" 개념. 당신은 스스로 선택하고 행동하는 주인공인가요, 아니면 누군가의 배경에 등장하는 NPC인가요? 10개의 질문으로 확인해보세요.',
    tags: ['NPC', '주인공', '자기계발', '밈', '인생'],
    emoji: '🎮',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
    questionCount: 10,
    trending: true,
  },

  // ─── 게임 ───
  {
    slug: 'reaction-tap',
    trending: true,
    category: 'game',
    type: 'game',
    title: '반응 속도 게임',
    subtitle: '1분 안에 얼마나 빠르게 반응할 수 있을까?',
    description: '화면이 바뀌는 순간 최대한 빠르게 탭하세요. 평균 반응 속도와 등급을 확인하고, 최고 기록에 도전해보세요.',
    tags: ['게임', '반응속도', '탭', '도전'],
    emoji: '⚡',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
  },
  {
    slug: 'color-memory',
    category: 'game',
    type: 'game',
    title: '색깔 기억 게임',
    subtitle: '몇 단계까지 기억할 수 있을까?',
    description: '색깔이 순서대로 점등됩니다. 순서를 기억하고 그대로 탭하세요! 한 단계씩 길어지는 시퀀스를 얼마나 기억할 수 있는지 도전해보세요. 전 세계적으로 사랑받는 기억력 게임입니다.',
    tags: ['게임', '기억력', '색깔', '도전', '집중력'],
    emoji: '🎨',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
  },
  {
    slug: 'number-memory',
    category: 'game',
    type: 'game',
    title: '숫자 기억 게임',
    subtitle: '몇 자리 숫자까지 기억할 수 있을까?',
    description: '숫자가 잠깐 보였다가 사라집니다. 기억해서 정확하게 입력해보세요! 숫자가 점점 길어져 어려워지는 두뇌 트레이닝 게임입니다.',
    tags: ['게임', '기억력', '숫자', '도전', '두뇌'],
    emoji: '🔢',
    inputSchema: [],
    adPolicy: { questionAds: 0, resultSlots: ['A', 'B'], coupangCount: 1 },
  },
];

export function getContentBySlug(slug: string): ContentEntry | undefined {
  return contentRegistry.find(c => c.slug === slug);
}

export function getContentByCategory(category: string): ContentEntry[] {
  return contentRegistry.filter(c => c.category === category);
}

export function getAllCategories(): { id: string; label: string; emoji: string }[] {
  return [
    { id: 'fortune', label: '운세', emoji: '🔮' },
    { id: 'test', label: '테스트', emoji: '📝' },
    { id: 'quiz', label: '퀴즈', emoji: '🧠' },
    { id: 'game', label: '게임', emoji: '🎮' },
  ];
}
